---
title: "dataloader"
author: "Sean Shen"
date: "`r Sys.Date()`"
output: html_document
---

# Combining Traits, Functional Connectome PCs, and Structural Connectome PCs

SHOULD RUN `pca-vae.Rmd` first, then run this to get the data

```{r}
library(R.matlab)
library(dplyr)
library(randomForest)

# --- 1. Load Structural (1065 Subjects) ---
s_data <- readMat("../data/raw/TNPCA_Result/TNPCA_Coeff_HCP_Structural_Connectome.mat")
# Get number of subjects dynamically
n_subs_struct <- length(s_data$sub.id)
s_coeffs <- matrix(s_data$PCA.Coeff, nrow = n_subs_struct, ncol = 60)
colnames(s_coeffs) <- paste0("Struct_PC", 1:60)
df_struct <- data.frame(Subject = as.vector(s_data$sub.id), s_coeffs)

# --- 2. Load Functional (1058 Subjects) ---
f_data <- readMat("../data/raw/TNPCA_Result/TNPCA_Coeff_HCP_Functional_Connectome.mat")
# Get number of subjects dynamically (It is 1058, not 1065)
n_subs_func <- length(f_data$network.subject.ids)
f_coeffs <- matrix(f_data$PCA.Coeff, nrow = n_subs_func, ncol = 60)
colnames(f_coeffs) <- paste0("Func_PC", 1:60)
df_func <- data.frame(Subject = as.vector(f_data$network.subject.ids), f_coeffs)

# --- 3. Merge Everything ---
traits1 <- read.csv("../data/raw/traits/table1_hcp.csv")
traits2 <- read.csv("../data/raw/traits/table2_hcp.csv")

# Should run pca-vae.rmd first
# Get PCA and VAE data
vae_df <- read.csv("../data/processed/vae_df.csv")
raw_pca_df <- read.csv("../data/processed/raw_pca_df.csv")


# Inner join will automatically keep only the subjects present in ALL files
# This results in the intersection (1058 subjects)
mega_data <- inner_join(traits1, traits2, by = "Subject") %>%
             inner_join(df_struct, by = "Subject") %>%
             inner_join(df_func, by = "Subject") %>%
  inner_join(vae_df, by = "Subject") %>%
  inner_join(raw_pca_df, by = "Subject") %>%




print(paste("Mega Dataset Loaded. Rows:", nrow(mega_data), "| Features:", ncol(mega_data)))
write.csv(mega_data, "../data/processed/full_data.csv")
```


```{r load from csv}
full_data <- read.csv("../data/processed/full_data.csv")
```


